# Generated by Django 3.0.2 on 2020-07-16 23:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('cmId', models.AutoField(primary_key=True, serialize=False)),
                ('cmText', models.CharField(default='还行', max_length=144)),
                ('cmT2S', models.SmallIntegerField(default=5)),
                ('cmS2T', models.SmallIntegerField(default=5)),
                ('cmTId', models.CharField(max_length=8)),
                ('cmSId', models.CharField(max_length=8)),
                ('cmCId', models.CharField(max_length=8)),
                ('cmTime', models.DateTimeField(default=datetime.datetime(2020, 7, 16, 23, 19, 8, 665005))),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('coId', models.AutoField(primary_key=True, serialize=False)),
                ('coTID', models.CharField(max_length=8)),
                ('coIntro', models.CharField(blank=True, max_length=144, null=True)),
                ('coTime', models.DateTimeField(default=datetime.datetime(2020, 7, 16, 23, 19, 8, 664010))),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('msId', models.AutoField(primary_key=True, serialize=False)),
                ('msTID', models.CharField(default='', max_length=8)),
                ('msSID', models.CharField(default='', max_length=8)),
                ('msText', models.CharField(blank=True, max_length=144, null=True)),
                ('msLikeCount', models.SmallIntegerField(default=0)),
                ('msDisLikeCount', models.SmallIntegerField(default=0)),
                ('msTime', models.DateTimeField(default=datetime.datetime(2020, 7, 16, 23, 19, 8, 664010))),
            ],
        ),
        migrations.CreateModel(
            name='star',
            fields=[
                ('starId', models.AutoField(primary_key=True, serialize=False)),
                ('starT2S', models.SmallIntegerField(default=5)),
                ('starS2T', models.SmallIntegerField(default=5)),
                ('starTId', models.CharField(max_length=8)),
                ('starSId', models.CharField(max_length=8)),
                ('starCId', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('studentId', models.AutoField(primary_key=True, serialize=False)),
                ('studentAlias', models.CharField(max_length=20, unique=True)),
                ('studentPwd', models.CharField(default='66666666', max_length=20)),
                ('studentPhone', models.CharField(default='13713800000', max_length=12)),
                ('studentGender', models.BooleanField(default=True)),
                ('studentAvatar', models.FilePathField(path='sayhi/avatar/', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('teacherId', models.AutoField(primary_key=True, serialize=False)),
                ('teacherAlias', models.CharField(max_length=20, unique=True)),
                ('teacherPwd', models.CharField(default='66666666', max_length=20)),
                ('teacherPhone', models.CharField(default='13713800000', max_length=12)),
                ('teacherGender', models.BooleanField(default=True)),
                ('teacherAvatar', models.FilePathField(path='sayhi/avatar/', unique=True)),
            ],
        ),
    ]
